global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "notification-retry-simulator"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8080"

rule_files:
  - /etc/prometheus/alerts.yml         